### ISSUE TITLE
DeepInspector: Generic backend: from RLAssist to that + DeepFix, CuBERT, AFL, etc.

### ISSUE THREAD

**Issue by schelian** [Globalhelpforall/qv_poc_server#1]
We want the ability to choose different backends.  This means some kind of abstraction over the tools' results--an standard for how results are formatted.

Some options are [SCARF ](https://github.com/mirswamp/swamp-scarf-db) and [SARIF](https://github.com/microsoft/sarif-tutorials).  Bart suggested the latter b/c it's a follow on the former.  SCARF hasn't been updated in 4 years, whereas SARIF has been updated 9 months ago.

@wyler0 please look at what ever SonarQube uses and reply to this thread to keep it all together

@mikevasan98, @aswinjose89 , @wyler0 , @jeremyforest , @busycsu let's make a decision -- probably tomorrow -- and start writing interface code b/t our respective tools & the agreed upon results standard.

**Comment by wyler0** [comment]
SonarQube stores analysis results in a database (with conversion tools to convert to other formats i.e. postgresql). It then suppors exporting results to PDF and XML.
Per [SonarQube Support](https://community.sonarsource.com/t/support-sarif-reports/34792):
 - SonarQube has **NO built in support for SARIF.** Note SARIF is an active repo (commit 21 days ago).
 - SCARF is not really used anywhere, and **no one has requested support for SCARF in SonarQube** as far as I can tell.

Regarding SARIF,
- SonarQube includes the [Generic Issue Import Format](https://docs.sonarqube.org/latest/analysis/generic-issue/) which can support importing SARIF if **we write a converter.**
- SonarQube uses **Java Based Plugins** which **we could develop** to include our custom analysis tools (doesn't seem terrible but definitely a learning curve)

**Comment by wyler0** [comment]
The decision is SARIF.

**Comment by schelian** [comment]
Mothballing until needed again; also changing the title to keep projects sorted.
