### ISSUE TITLE
DeepInspector: CI/CD for the server

### ISSUE THREAD

**Issue by schelian** [Globalhelpforall/qv_poc_server#2]
Another thing we need is the ability to run our tools after a check in is done.  There may also be some "smarts" in how the tools are run (e.g., if someone just changed the README or code in a comment, then there's no need to re-run the tests) but we can save that for later.

@wyler0 can you please take a look to see how SonarQube integrates with GitHub and reply to this thread.  We can adapt their patterns to our systems.  I know you're looking at a lot so please look at the output standard first, then this.

@mikevasan98, @aswinjose89 , @wyler0 , @jeremyforest , @busycsu

**Comment by wyler0** [comment]
SonarQube support integration with **Github** via a custom java RESTful API wrapper. It supports **Jenkins** automation via running a SonarQube installation within Jenkins.

Github:
- Git integration is supported out of the box with a pure Java implementation (no git cli needed)
- Primarily relies on webhooks for automating actions + [java implementation of the git API](https://github.com/SonarSource/sonarqube/blob/900af07a23832dc8357eb49c3dd997976686ff29/server/sonar-auth-github/src/main/java/org/sonar/auth/github/GitHubRestClient.java) for interacting with users, projects and repos and [here](https://github.com/SonarSource/sonarqube/tree/900af07a23832dc8357eb49c3dd997976686ff29/server/sonar-webserver-webapi/src/main/java/org/sonar/server/almintegration/ws/github) and [here](https://github.com/SonarSource/sonarqube/tree/master/server/sonar-auth-github/src/main/java/org/sonar/auth/github).
- The github Marketplace has a [SonarQube action](https://github.com/marketplace/actions/official-sonarqube-scan) that runs sonarqube against your repo.

Conclusion: A good Java developer could clone the relevant Java Github API wrapper (its kind of scattered in the repo but regardless) into a different project. However, it would be a lot of work to clone all of the interactions between SonarQube & Github (ex.

**Comment by wyler0** [comment]
- What CI/CD integration pattern / tools would the Navy prefer?
- Manual implementation probably the best path to take.

**Comment by schelian** [comment]
Mothballing until needed again; also changing the title to keep projects sorted.
